// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';

// User customer
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL';

// User info Get and Update
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';

// all customer addresses
export const GET_ALL_CUSTOMER_INFO_SUCCESS = 'GET_ALL_CUSTOMER_INFO_SUCCESS';
export const GET_ALL_CUSTOMER_INFO_FAIL = 'GET_ALL_CUSTOMER_INFO_FAIL';

export const GET_ALL_CUSTOMER_INFO_DETAIL_FAIL =
  'GET_ALL_CUSTOMER_INFO_DETAIL_FAIL';
export const GET_ALL_CUSTOMER_INFO_DETAIL_SUCCESS =
  'GET_ALL_CUSTOMER_INFO_DETAIL_SUCCESS';

// get each address details
export const GET_USER_ADDRESS_SUCCESS = 'GET_USER_ADDRESS_SUCCESS';
export const GET_USER_ADDRESS_FAIL = 'GET_USER_ADDRESS_FAIL';

// add address details
export const ADD_USER_ADDRESS_SUCCESS = 'ADD_USER_ADDRESS_SUCCESS';
export const ADD_USER_ADDRESS_FAIL = 'ADD_USER_ADDRESS_FAIL';

// add address details to customer address
export const ADD_USER_ADDRESS_TO_CUSTOMER_SUCCESS =
  'ADD_USER_ADDRESS_TO_CUSTOMER_SUCCESS';
export const ADD_USER_ADDRESS_TO_CUSTOMER_FAIL =
  'ADD_USER_ADDRESS_TO_CUSTOMER_FAIL';

// update address details
export const UPDATE_ADDRESS_DETAIL_SUCCESS = 'UPDATE_ADDRESS_DETAIL_SUCCESS';
export const UPDATE_ADDRESS_DETAIL_FAIL = 'UPDATE_ADDRESS_DETAIL_FAIL';

// delete address details
export const DELETE_ADDRESS_DETAIL_SUCCESS = 'DELETE_ADDRESS_DETAIL_SUCCESS';
export const DELETE_ADDRESS_DETAIL_FAIL = 'DELETE_ADDRESS_DETAIL_FAIL';
